
export enum RequiredTransform {
  'SYNC_TO_ASYNC' = 'SYNC_TO_ASYNC',
  'ASYNC_AWAIT' = 'ASYNC_AWAIT',
  'PROMISE_ALL' = 'PROMISE_ALL',
  'FOR_OF_LOOP' = 'FOR_OF_LOOP',
  'FOR_EACH_TO_MAP' = 'FOR_EACH_TO_MAP'
}
